### ISSUE TITLE
Is there a way to limit calculated combinations to just 1 result

### ISSUE THREAD

**Issue by ddooley** [snshn/genex-js#1]
I'm interested in getting just the first possibility of a regex.  e,g. the first decimal in /0\.\d+/ .I was hoping to avoid CPU of generating all possibilities before running the callback to exit at first result.

Thanks,

Damion

**Comment by snshn** [comment]
I think this is the way to go https://github.com/fent/randexp.js

**Comment by ddooley** [comment]
Ah, well that is where I started and it is great.  But they randomize choices across alternatives, e.g. (a|b|c) yeilds any of a,b,c randomly, rather than a, then b, then c.  I was hoping for the latter.

**Comment by ddooley** [comment]
Managed to find a solution with randexp - by tuning randomizing function always to select first value.
Thanks for your time!
